"""add_source_packages_and_chat

Revision ID: 4b4dbd41c801
Revises: bb7a1076e057
Create Date: 2026-07-20 22:11:00.104192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4dbd41c801'
down_revision: Union[str, Sequence[str], None] = 'bb7a1076e057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('scope_type', sa.String(length=40), nullable=False),
    sa.Column('scope_filters', sa.JSON(), nullable=False),
    sa.Column('provider_connection_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_chat_sessions_case_id'), 'case_chat_sessions', ['case_id'], unique=False)
    op.create_table('analysis_source_packages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_session_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_session_id'], ['analysis_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_source_packages_analysis_session_id'), 'analysis_source_packages', ['analysis_session_id'], unique=False)
    op.create_table('case_chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cited_evidence', sa.JSON(), nullable=False),
    sa.Column('provider_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['case_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_chat_messages_session_id'), 'case_chat_messages', ['session_id'], unique=False)
    op.create_table('analysis_source_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_ref', sa.String(length=700), nullable=False),
    sa.Column('source_label', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['analysis_source_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_source_items_package_id'), 'analysis_source_items', ['package_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_source_items_package_id'), table_name='analysis_source_items')
    op.drop_table('analysis_source_items')
    op.drop_index(op.f('ix_case_chat_messages_session_id'), table_name='case_chat_messages')
    op.drop_table('case_chat_messages')
    op.drop_index(op.f('ix_analysis_source_packages_analysis_session_id'), table_name='analysis_source_packages')
    op.drop_table('analysis_source_packages')
    op.drop_index(op.f('ix_case_chat_sessions_case_id'), table_name='case_chat_sessions')
    op.drop_table('case_chat_sessions')
    # ### end Alembic commands ###
