"""add_osint_findings_events_snapshots

Revision ID: 5b7a8fee17f6
Revises: f88ce5376567
Create Date: 2026-07-20 21:42:46.014797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7a8fee17f6'
down_revision: Union[str, Sequence[str], None] = 'f88ce5376567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpora',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('relative_path', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('indexed_file_count', sa.Integer(), nullable=False),
    sa.Column('total_bytes', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('scan_summary', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corpora_status'), 'corpora', ['status'], unique=False)
    op.create_index('ix_corpus_status_created', 'corpora', ['status', 'created_at'], unique=False)
    op.create_table('analysis_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_session_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_session_id'], ['analysis_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_events_analysis_session_id'), 'analysis_events', ['analysis_session_id'], unique=False)
    op.create_index(op.f('ix_analysis_events_event_type'), 'analysis_events', ['event_type'], unique=False)
    op.create_table('analysis_stage_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('analysis_session_id', sa.String(length=36), nullable=False),
    sa.Column('phase', sa.String(length=60), nullable=False),
    sa.Column('persona_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('provider_connection_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_session_id'], ['analysis_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_stage_runs_analysis_session_id'), 'analysis_stage_runs', ['analysis_session_id'], unique=False)
    op.create_index(op.f('ix_analysis_stage_runs_phase'), 'analysis_stage_runs', ['phase'], unique=False)
    op.create_table('corpus_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('corpus_id', sa.String(length=36), nullable=False),
    sa.Column('relative_path', sa.String(length=1400), nullable=False),
    sa.Column('media_type', sa.String(length=160), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('extractor', sa.String(length=80), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('document_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpora.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corpus_id', 'relative_path')
    )
    op.create_index(op.f('ix_corpus_documents_corpus_id'), 'corpus_documents', ['corpus_id'], unique=False)
    op.create_index(op.f('ix_corpus_documents_sha256'), 'corpus_documents', ['sha256'], unique=False)
    op.create_table('osint_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('osint_run_id', sa.String(length=36), nullable=False),
    sa.Column('profile_url', sa.String(length=2000), nullable=False),
    sa.Column('site', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=300), nullable=False),
    sa.Column('http_status', sa.String(length=10), nullable=True),
    sa.Column('identity_status', sa.String(length=40), nullable=False),
    sa.Column('verification_status', sa.String(length=40), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['osint_run_id'], ['osint_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('osint_run_id', 'dedup_hash')
    )
    op.create_index(op.f('ix_osint_findings_dedup_hash'), 'osint_findings', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_osint_findings_osint_run_id'), 'osint_findings', ['osint_run_id'], unique=False)
    op.create_table('osint_run_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('osint_run_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['osint_run_id'], ['osint_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_osint_run_events_event_type'), 'osint_run_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_osint_run_events_osint_run_id'), 'osint_run_events', ['osint_run_id'], unique=False)
    op.create_index('ix_osint_run_events_seq', 'osint_run_events', ['osint_run_id', 'sequence'], unique=False)
    op.create_table('osint_finding_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('connector', sa.String(length=80), nullable=False),
    sa.Column('site', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['osint_findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_osint_finding_sources_finding_id'), 'osint_finding_sources', ['finding_id'], unique=False)
    op.create_table('page_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('page_text', sa.Text(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=False),
    sa.Column('extractor', sa.String(length=80), nullable=False),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['osint_findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_snapshots_content_hash'), 'page_snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_page_snapshots_finding_id'), 'page_snapshots', ['finding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_snapshots_finding_id'), table_name='page_snapshots')
    op.drop_index(op.f('ix_page_snapshots_content_hash'), table_name='page_snapshots')
    op.drop_table('page_snapshots')
    op.drop_index(op.f('ix_osint_finding_sources_finding_id'), table_name='osint_finding_sources')
    op.drop_table('osint_finding_sources')
    op.drop_index('ix_osint_run_events_seq', table_name='osint_run_events')
    op.drop_index(op.f('ix_osint_run_events_osint_run_id'), table_name='osint_run_events')
    op.drop_index(op.f('ix_osint_run_events_event_type'), table_name='osint_run_events')
    op.drop_table('osint_run_events')
    op.drop_index(op.f('ix_osint_findings_osint_run_id'), table_name='osint_findings')
    op.drop_index(op.f('ix_osint_findings_dedup_hash'), table_name='osint_findings')
    op.drop_table('osint_findings')
    op.drop_index(op.f('ix_corpus_documents_sha256'), table_name='corpus_documents')
    op.drop_index(op.f('ix_corpus_documents_corpus_id'), table_name='corpus_documents')
    op.drop_table('corpus_documents')
    op.drop_index(op.f('ix_analysis_stage_runs_phase'), table_name='analysis_stage_runs')
    op.drop_index(op.f('ix_analysis_stage_runs_analysis_session_id'), table_name='analysis_stage_runs')
    op.drop_table('analysis_stage_runs')
    op.drop_index(op.f('ix_analysis_events_event_type'), table_name='analysis_events')
    op.drop_index(op.f('ix_analysis_events_analysis_session_id'), table_name='analysis_events')
    op.drop_table('analysis_events')
    op.drop_index('ix_corpus_status_created', table_name='corpora')
    op.drop_index(op.f('ix_corpora_status'), table_name='corpora')
    op.drop_table('corpora')
    # ### end Alembic commands ###
