"""add_instagram_import_tables

Revision ID: bb7a1076e057
Revises: 5b7a8fee17f6
Create Date: 2026-07-20 21:43:38.841469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb7a1076e057'
down_revision: Union[str, Sequence[str], None] = '5b7a8fee17f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('import_root', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('archive_owner_username', sa.String(length=200), nullable=True),
    sa.Column('archive_owner_display_name', sa.String(length=300), nullable=True),
    sa.Column('archive_owner_confirmed', sa.Boolean(), nullable=False),
    sa.Column('total_conversations', sa.Integer(), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('import_summary', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_status'), 'import_batches', ['status'], unique=False)
    op.create_table('imported_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('import_batch_id', sa.String(length=36), nullable=False),
    sa.Column('source_conversation_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('earliest_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('participant_names', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imported_conversations_import_batch_id'), 'imported_conversations', ['import_batch_id'], unique=False)
    op.create_table('imported_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('import_batch_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=True),
    sa.Column('is_archive_owner', sa.Boolean(), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('profile_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imported_profiles_import_batch_id'), 'imported_profiles', ['import_batch_id'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['imported_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['imported_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_participants_conversation_id'), 'conversation_participants', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_name'), 'conversation_participants', ['name'], unique=False)
    op.create_table('imported_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender_name', sa.String(length=300), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_normalized', sa.Text(), nullable=True),
    sa.Column('share_link', sa.String(length=2000), nullable=True),
    sa.Column('has_media', sa.Boolean(), nullable=False),
    sa.Column('media_refs', sa.JSON(), nullable=False),
    sa.Column('reactions', sa.JSON(), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_message_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['imported_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'source_message_id')
    )
    op.create_index(op.f('ix_imported_messages_content_hash'), 'imported_messages', ['content_hash'], unique=False)
    op.create_index(op.f('ix_imported_messages_conversation_id'), 'imported_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_imported_messages_sender_name'), 'imported_messages', ['sender_name'], unique=False)
    op.create_index(op.f('ix_imported_messages_timestamp_ms'), 'imported_messages', ['timestamp_ms'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imported_messages_timestamp_ms'), table_name='imported_messages')
    op.drop_index(op.f('ix_imported_messages_sender_name'), table_name='imported_messages')
    op.drop_index(op.f('ix_imported_messages_conversation_id'), table_name='imported_messages')
    op.drop_index(op.f('ix_imported_messages_content_hash'), table_name='imported_messages')
    op.drop_table('imported_messages')
    op.drop_index(op.f('ix_conversation_participants_name'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_conversation_id'), table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index(op.f('ix_imported_profiles_import_batch_id'), table_name='imported_profiles')
    op.drop_table('imported_profiles')
    op.drop_index(op.f('ix_imported_conversations_import_batch_id'), table_name='imported_conversations')
    op.drop_table('imported_conversations')
    op.drop_index(op.f('ix_import_batches_status'), table_name='import_batches')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
